apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: unp6mkzin-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: unp6mkzin-go 
  name: unp6mkzin-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: unp6mkzin-go 
